# coding: utf-8

"""
    Respeecher API

    API for interacting with Respeecher services, including key and session management, and calibration functionalities.  # noqa: E501

    OpenAPI spec version: 1.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

import unittest

import respeecher
from respeecher.api.default_api import DefaultApi  # noqa: E501
from respeecher.rest import ApiException


class TestDefaultApi(unittest.TestCase):
    """DefaultApi unit test stubs"""

    def setUp(self):
        self.api = DefaultApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_create_calibration(self):
        """Test case for create_calibration

        Create a new Calibration  # noqa: E501
        """
        pass

    def test_create_folder(self):
        """Test case for create_folder

        Create a folder  # noqa: E501
        """
        pass

    def test_create_note(self):
        """Test case for create_note

        Create a note associated with a recording  # noqa: E501
        """
        pass

    def test_create_order(self):
        """Test case for create_order

        Create a conversion order  # noqa: E501
        """
        pass

    def test_create_original_recording(self):
        """Test case for create_original_recording

        Create an original recording  # noqa: E501
        """
        pass

    def test_create_project(self):
        """Test case for create_project

        Create a new project  # noqa: E501
        """
        pass

    def test_create_tts_recording(self):
        """Test case for create_tts_recording

        Create an original text-to-speech recording  # noqa: E501
        """
        pass

    def test_delete_api_key(self):
        """Test case for delete_api_key

        Delete the API key associated with your account  # noqa: E501
        """
        pass

    def test_delete_calibration(self):
        """Test case for delete_calibration

        Delete a calibration  # noqa: E501
        """
        pass

    def test_delete_folder(self):
        """Test case for delete_folder

        Delete a folder  # noqa: E501
        """
        pass

    def test_delete_note(self):
        """Test case for delete_note

        Delete a note  # noqa: E501
        """
        pass

    def test_delete_project(self):
        """Test case for delete_project

        Delete a project  # noqa: E501
        """
        pass

    def test_delete_recording(self):
        """Test case for delete_recording

        Delete a recording  # noqa: E501
        """
        pass

    def test_enable_calibration(self):
        """Test case for enable_calibration

        Set a calibration as the default enabled calibration  # noqa: E501
        """
        pass

    def test_export_project(self):
        """Test case for export_project

        Export a project  # noqa: E501
        """
        pass

    def test_favorite_voice(self):
        """Test case for favorite_voice

        Mark a voice as a favorite  # noqa: E501
        """
        pass

    def test_generate_api_key(self):
        """Test case for generate_api_key

        Generate a new API key  # noqa: E501
        """
        pass

    def test_get_accent_samples(self):
        """Test case for get_accent_samples

        Get samples available for an accent  # noqa: E501
        """
        pass

    def test_get_account_statistics(self):
        """Test case for get_account_statistics

        Get the statistics for your account  # noqa: E501
        """
        pass

    def test_get_calibration(self):
        """Test case for get_calibration

        Get a calibration by its ID  # noqa: E501
        """
        pass

    def test_get_credits(self):
        """Test case for get_credits

        Get the credits available to your account  # noqa: E501
        """
        pass

    def test_get_folder_by_id(self):
        """Test case for get_folder_by_id

        Get a folder by its ID  # noqa: E501
        """
        pass

    def test_get_folders_statistics(self):
        """Test case for get_folders_statistics

        Get statistics for a list of folders  # noqa: E501
        """
        pass

    def test_get_project_by_url(self):
        """Test case for get_project_by_url

        Get a project by its URL  # noqa: E501
        """
        pass

    def test_get_projects_statistics(self):
        """Test case for get_projects_statistics

        Get statistics for a list of projects  # noqa: E501
        """
        pass

    def test_get_recording_by_id(self):
        """Test case for get_recording_by_id

        Get a recording by its ID  # noqa: E501
        """
        pass

    def test_list_calibrations(self):
        """Test case for list_calibrations

        Get a list of calibrations associated with your account  # noqa: E501
        """
        pass

    def test_list_conversions(self):
        """Test case for list_conversions

        Get a list of the conversions for an original recording  # noqa: E501
        """
        pass

    def test_list_folders(self):
        """Test case for list_folders

        Get a list of the folders in a project  # noqa: E501
        """
        pass

    def test_list_original_recordings(self):
        """Test case for list_original_recordings

        Get a list of the original recordings in a folder  # noqa: E501
        """
        pass

    def test_list_projects(self):
        """Test case for list_projects

        Get a list of your projects  # noqa: E501
        """
        pass

    def test_list_recordings(self):
        """Test case for list_recordings

        Get a list of recordings for a specified folder or project  # noqa: E501
        """
        pass

    def test_list_tts_voices(self):
        """Test case for list_tts_voices

        Get a list of the available TTS voices  # noqa: E501
        """
        pass

    def test_list_voices(self):
        """Test case for list_voices

        Get a list of the voices available  # noqa: E501
        """
        pass

    def test_login(self):
        """Test case for login

        Log in to an account and start a new session  # noqa: E501
        """
        pass

    def test_logout(self):
        """Test case for logout

        End your session  # noqa: E501
        """
        pass

    def test_rename_folder(self):
        """Test case for rename_folder

        Rename a folder  # noqa: E501
        """
        pass

    def test_retry_order_v2(self):
        """Test case for retry_order_v2

        Retry a conversion order for a specific original  # noqa: E501
        """
        pass

    def test_search_voices(self):
        """Test case for search_voices

        Search for a voice by its name  # noqa: E501
        """
        pass

    def test_set_voice_settings(self):
        """Test case for set_voice_settings

        Set the settings for a voice  # noqa: E501
        """
        pass

    def test_update_note(self):
        """Test case for update_note

        Update a note  # noqa: E501
        """
        pass

    def test_update_project(self):
        """Test case for update_project

        Change the name of a project  # noqa: E501
        """
        pass

    def test_update_recording(self):
        """Test case for update_recording

        Update a recording  # noqa: E501
        """
        pass


if __name__ == '__main__':
    unittest.main()
