# coding: utf-8

"""
    Respeecher API

    API for interacting with Respeecher services, including key and session management, and calibration functionalities.  # noqa: E501

    OpenAPI spec version: 1.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

import unittest

import respeecher
from respeecher.models.api_recordings_body import ApiRecordingsBody  # noqa: E501
from respeecher.rest import ApiException


class TestApiRecordingsBody(unittest.TestCase):
    """ApiRecordingsBody unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testApiRecordingsBody(self):
        """Test ApiRecordingsBody"""
        # FIXME: construct object with mandatory attributes with example values
        # model = respeecher.models.api_recordings_body.ApiRecordingsBody()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
