# coding: utf-8

"""
    Respeecher API

    API for interacting with Respeecher services, including key and session management, and calibration functionalities.  # noqa: E501

    OpenAPI spec version: 1.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

import unittest

import respeecher
from respeecher.models.api_login_body import ApiLoginBody  # noqa: E501
from respeecher.rest import ApiException


class TestApiLoginBody(unittest.TestCase):
    """ApiLoginBody unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testApiLoginBody(self):
        """Test ApiLoginBody"""
        # FIXME: construct object with mandatory attributes with example values
        # model = respeecher.models.api_login_body.ApiLoginBody()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
