# coding: utf-8

"""
    Respeecher API

    API for interacting with Respeecher services, including key and session management, and calibration functionalities.  # noqa: E501

    OpenAPI spec version: 1.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

import unittest

import respeecher
from respeecher.models.project_list_response import ProjectListResponse  # noqa: E501
from respeecher.rest import ApiException


class TestProjectListResponse(unittest.TestCase):
    """ProjectListResponse unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testProjectListResponse(self):
        """Test ProjectListResponse"""
        # FIXME: construct object with mandatory attributes with example values
        # model = respeecher.models.project_list_response.ProjectListResponse()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
