# coding: utf-8

"""
    Respeecher API

    API for interacting with Respeecher services, including key and session management, and calibration functionalities.  # noqa: E501

    OpenAPI spec version: 1.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

import unittest

import respeecher
from respeecher.models.projects_statistics_response import ProjectsStatisticsResponse  # noqa: E501
from respeecher.rest import ApiException


class TestProjectsStatisticsResponse(unittest.TestCase):
    """ProjectsStatisticsResponse unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testProjectsStatisticsResponse(self):
        """Test ProjectsStatisticsResponse"""
        # FIXME: construct object with mandatory attributes with example values
        # model = respeecher.models.projects_statistics_response.ProjectsStatisticsResponse()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
