# coding: utf-8

"""
    Respeecher API

    API for interacting with Respeecher services, including key and session management, and calibration functionalities.  # noqa: E501

    OpenAPI spec version: 1.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

import unittest

import respeecher
from respeecher.models.account_statistics_conversions import AccountStatisticsConversions  # noqa: E501
from respeecher.rest import ApiException


class TestAccountStatisticsConversions(unittest.TestCase):
    """AccountStatisticsConversions unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testAccountStatisticsConversions(self):
        """Test AccountStatisticsConversions"""
        # FIXME: construct object with mandatory attributes with example values
        # model = respeecher.models.account_statistics_conversions.AccountStatisticsConversions()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
