# coding: utf-8

"""
    Respeecher API

    API for interacting with Respeecher services, including key and session management, and calibration functionalities.  # noqa: E501

    OpenAPI spec version: 1.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

import unittest

import respeecher
from respeecher.models.favorite_voice_id_body import FavoriteVoiceIdBody  # noqa: E501
from respeecher.rest import ApiException


class TestFavoriteVoiceIdBody(unittest.TestCase):
    """FavoriteVoiceIdBody unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testFavoriteVoiceIdBody(self):
        """Test FavoriteVoiceIdBody"""
        # FIXME: construct object with mandatory attributes with example values
        # model = respeecher.models.favorite_voice_id_body.FavoriteVoiceIdBody()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
