# coding: utf-8

"""
    Respeecher API

    API for interacting with Respeecher services, including key and session management, and calibration functionalities.  # noqa: E501

    OpenAPI spec version: 1.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

import unittest

import respeecher
from respeecher.models.folders_folder_id_body import FoldersFolderIdBody  # noqa: E501
from respeecher.rest import ApiException


class TestFoldersFolderIdBody(unittest.TestCase):
    """FoldersFolderIdBody unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testFoldersFolderIdBody(self):
        """Test FoldersFolderIdBody"""
        # FIXME: construct object with mandatory attributes with example values
        # model = respeecher.models.folders_folder_id_body.FoldersFolderIdBody()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
