# coding: utf-8

"""
    Respeecher API

    API for interacting with Respeecher services, including key and session management, and calibration functionalities.  # noqa: E501

    OpenAPI spec version: 1.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

import unittest

import respeecher
from respeecher.models.api_calibration_body import ApiCalibrationBody  # noqa: E501
from respeecher.rest import ApiException


class TestApiCalibrationBody(unittest.TestCase):
    """ApiCalibrationBody unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testApiCalibrationBody(self):
        """Test ApiCalibrationBody"""
        # FIXME: construct object with mandatory attributes with example values
        # model = respeecher.models.api_calibration_body.ApiCalibrationBody()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
