# coding: utf-8

"""
    Respeecher API

    API for interacting with Respeecher services, including key and session management, and calibration functionalities.  # noqa: E501

    OpenAPI spec version: 1.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

import unittest

import respeecher
from respeecher.models.recording_list_response import RecordingListResponse  # noqa: E501
from respeecher.rest import ApiException


class TestRecordingListResponse(unittest.TestCase):
    """RecordingListResponse unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testRecordingListResponse(self):
        """Test RecordingListResponse"""
        # FIXME: construct object with mandatory attributes with example values
        # model = respeecher.models.recording_list_response.RecordingListResponse()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
