# coding: utf-8

"""
    Respeecher API

    API for interacting with Respeecher services, including key and session management, and calibration functionalities.  # noqa: E501

    OpenAPI spec version: 1.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

import unittest

import respeecher
from respeecher.models.folder_statistics_stats import FolderStatisticsStats  # noqa: E501
from respeecher.rest import ApiException


class TestFolderStatisticsStats(unittest.TestCase):
    """FolderStatisticsStats unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testFolderStatisticsStats(self):
        """Test FolderStatisticsStats"""
        # FIXME: construct object with mandatory attributes with example values
        # model = respeecher.models.folder_statistics_stats.FolderStatisticsStats()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
