# coding: utf-8

"""
    Respeecher API

    API for interacting with Respeecher services, including key and session management, and calibration functionalities.  # noqa: E501

    OpenAPI spec version: 1.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

import unittest

import respeecher
from respeecher.models.accent_samples_response import AccentSamplesResponse  # noqa: E501
from respeecher.rest import ApiException


class TestAccentSamplesResponse(unittest.TestCase):
    """AccentSamplesResponse unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testAccentSamplesResponse(self):
        """Test AccentSamplesResponse"""
        # FIXME: construct object with mandatory attributes with example values
        # model = respeecher.models.accent_samples_response.AccentSamplesResponse()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
