# coding: utf-8

"""
    Respeecher API

    API for interacting with Respeecher services, including key and session management, and calibration functionalities.  # noqa: E501

    OpenAPI spec version: 1.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

import unittest

import respeecher
from respeecher.models.folders_statistics_response import FoldersStatisticsResponse  # noqa: E501
from respeecher.rest import ApiException


class TestFoldersStatisticsResponse(unittest.TestCase):
    """FoldersStatisticsResponse unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testFoldersStatisticsResponse(self):
        """Test FoldersStatisticsResponse"""
        # FIXME: construct object with mandatory attributes with example values
        # model = respeecher.models.folders_statistics_response.FoldersStatisticsResponse()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
