# coding: utf-8

"""
    Respeecher API

    API for interacting with Respeecher services, including key and session management, and calibration functionalities.  # noqa: E501

    OpenAPI spec version: 1.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

import pprint
import re  # noqa: F401

import six

class AccountStatisticsTimeConverted(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'total': 'int',
        'current_month': 'int',
        'previous_monthes': 'list[AccountStatisticsTimeConvertedPreviousMonthes]'
    }

    attribute_map = {
        'total': 'total',
        'current_month': 'current_month',
        'previous_monthes': 'previous_monthes'
    }

    def __init__(self, total=None, current_month=None, previous_monthes=None):  # noqa: E501
        """AccountStatisticsTimeConverted - a model defined in Swagger"""  # noqa: E501
        self._total = None
        self._current_month = None
        self._previous_monthes = None
        self.discriminator = None
        if total is not None:
            self.total = total
        if current_month is not None:
            self.current_month = current_month
        if previous_monthes is not None:
            self.previous_monthes = previous_monthes

    @property
    def total(self):
        """Gets the total of this AccountStatisticsTimeConverted.  # noqa: E501


        :return: The total of this AccountStatisticsTimeConverted.  # noqa: E501
        :rtype: int
        """
        return self._total

    @total.setter
    def total(self, total):
        """Sets the total of this AccountStatisticsTimeConverted.


        :param total: The total of this AccountStatisticsTimeConverted.  # noqa: E501
        :type: int
        """

        self._total = total

    @property
    def current_month(self):
        """Gets the current_month of this AccountStatisticsTimeConverted.  # noqa: E501


        :return: The current_month of this AccountStatisticsTimeConverted.  # noqa: E501
        :rtype: int
        """
        return self._current_month

    @current_month.setter
    def current_month(self, current_month):
        """Sets the current_month of this AccountStatisticsTimeConverted.


        :param current_month: The current_month of this AccountStatisticsTimeConverted.  # noqa: E501
        :type: int
        """

        self._current_month = current_month

    @property
    def previous_monthes(self):
        """Gets the previous_monthes of this AccountStatisticsTimeConverted.  # noqa: E501


        :return: The previous_monthes of this AccountStatisticsTimeConverted.  # noqa: E501
        :rtype: list[AccountStatisticsTimeConvertedPreviousMonthes]
        """
        return self._previous_monthes

    @previous_monthes.setter
    def previous_monthes(self, previous_monthes):
        """Sets the previous_monthes of this AccountStatisticsTimeConverted.


        :param previous_monthes: The previous_monthes of this AccountStatisticsTimeConverted.  # noqa: E501
        :type: list[AccountStatisticsTimeConvertedPreviousMonthes]
        """

        self._previous_monthes = previous_monthes

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value
        if issubclass(AccountStatisticsTimeConverted, dict):
            for key, value in self.items():
                result[key] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, AccountStatisticsTimeConverted):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        return not self == other
