# coding: utf-8

"""
    Respeecher API

    API for interacting with Respeecher services, including key and session management, and calibration functionalities.  # noqa: E501

    OpenAPI spec version: 1.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

import pprint
import re  # noqa: F401

import six

class ApiRecordingsBody(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'data': 'str',
        'parent_folder_id': 'str',
        'microphone': 'str',
        'label': 'str'
    }

    attribute_map = {
        'data': 'data',
        'parent_folder_id': 'parent_folder_id',
        'microphone': 'microphone',
        'label': 'label'
    }

    def __init__(self, data=None, parent_folder_id=None, microphone=None, label=None):  # noqa: E501
        """ApiRecordingsBody - a model defined in Swagger"""  # noqa: E501
        self._data = None
        self._parent_folder_id = None
        self._microphone = None
        self._label = None
        self.discriminator = None
        if data is not None:
            self.data = data
        if parent_folder_id is not None:
            self.parent_folder_id = parent_folder_id
        if microphone is not None:
            self.microphone = microphone
        if label is not None:
            self.label = label

    @property
    def data(self):
        """Gets the data of this ApiRecordingsBody.  # noqa: E501

        The audio binary data  # noqa: E501

        :return: The data of this ApiRecordingsBody.  # noqa: E501
        :rtype: str
        """
        return self._data

    @data.setter
    def data(self, data):
        """Sets the data of this ApiRecordingsBody.

        The audio binary data  # noqa: E501

        :param data: The data of this ApiRecordingsBody.  # noqa: E501
        :type: str
        """

        self._data = data

    @property
    def parent_folder_id(self):
        """Gets the parent_folder_id of this ApiRecordingsBody.  # noqa: E501


        :return: The parent_folder_id of this ApiRecordingsBody.  # noqa: E501
        :rtype: str
        """
        return self._parent_folder_id

    @parent_folder_id.setter
    def parent_folder_id(self, parent_folder_id):
        """Sets the parent_folder_id of this ApiRecordingsBody.


        :param parent_folder_id: The parent_folder_id of this ApiRecordingsBody.  # noqa: E501
        :type: str
        """

        self._parent_folder_id = parent_folder_id

    @property
    def microphone(self):
        """Gets the microphone of this ApiRecordingsBody.  # noqa: E501

        Name of the microphone used, set to 'file' if uploading a file  # noqa: E501

        :return: The microphone of this ApiRecordingsBody.  # noqa: E501
        :rtype: str
        """
        return self._microphone

    @microphone.setter
    def microphone(self, microphone):
        """Sets the microphone of this ApiRecordingsBody.

        Name of the microphone used, set to 'file' if uploading a file  # noqa: E501

        :param microphone: The microphone of this ApiRecordingsBody.  # noqa: E501
        :type: str
        """

        self._microphone = microphone

    @property
    def label(self):
        """Gets the label of this ApiRecordingsBody.  # noqa: E501


        :return: The label of this ApiRecordingsBody.  # noqa: E501
        :rtype: str
        """
        return self._label

    @label.setter
    def label(self, label):
        """Sets the label of this ApiRecordingsBody.


        :param label: The label of this ApiRecordingsBody.  # noqa: E501
        :type: str
        """

        self._label = label

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value
        if issubclass(ApiRecordingsBody, dict):
            for key, value in self.items():
                result[key] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, ApiRecordingsBody):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        return not self == other
