# coding: utf-8

"""
    Respeecher API

    API for interacting with Respeecher services, including key and session management, and calibration functionalities.  # noqa: E501

    OpenAPI spec version: 1.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

import pprint
import re  # noqa: F401

import six

class InlineResponse2001(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'user': 'object',
        'csrf_token': 'str',
        'session_duration': 'int'
    }

    attribute_map = {
        'user': 'user',
        'csrf_token': 'csrf_token',
        'session_duration': 'session_duration'
    }

    def __init__(self, user=None, csrf_token=None, session_duration=None):  # noqa: E501
        """InlineResponse2001 - a model defined in Swagger"""  # noqa: E501
        self._user = None
        self._csrf_token = None
        self._session_duration = None
        self.discriminator = None
        if user is not None:
            self.user = user
        if csrf_token is not None:
            self.csrf_token = csrf_token
        if session_duration is not None:
            self.session_duration = session_duration

    @property
    def user(self):
        """Gets the user of this InlineResponse2001.  # noqa: E501


        :return: The user of this InlineResponse2001.  # noqa: E501
        :rtype: object
        """
        return self._user

    @user.setter
    def user(self, user):
        """Sets the user of this InlineResponse2001.


        :param user: The user of this InlineResponse2001.  # noqa: E501
        :type: object
        """

        self._user = user

    @property
    def csrf_token(self):
        """Gets the csrf_token of this InlineResponse2001.  # noqa: E501


        :return: The csrf_token of this InlineResponse2001.  # noqa: E501
        :rtype: str
        """
        return self._csrf_token

    @csrf_token.setter
    def csrf_token(self, csrf_token):
        """Sets the csrf_token of this InlineResponse2001.


        :param csrf_token: The csrf_token of this InlineResponse2001.  # noqa: E501
        :type: str
        """

        self._csrf_token = csrf_token

    @property
    def session_duration(self):
        """Gets the session_duration of this InlineResponse2001.  # noqa: E501


        :return: The session_duration of this InlineResponse2001.  # noqa: E501
        :rtype: int
        """
        return self._session_duration

    @session_duration.setter
    def session_duration(self, session_duration):
        """Sets the session_duration of this InlineResponse2001.


        :param session_duration: The session_duration of this InlineResponse2001.  # noqa: E501
        :type: int
        """

        self._session_duration = session_duration

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value
        if issubclass(InlineResponse2001, dict):
            for key, value in self.items():
                result[key] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, InlineResponse2001):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        return not self == other
