# coding: utf-8

"""
    Respeecher API

    API for interacting with Respeecher services, including key and session management, and calibration functionalities.  # noqa: E501

    OpenAPI spec version: 1.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

import pprint
import re  # noqa: F401

import six

class ProjectStatistics(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'project_id': 'str',
        'time_converted': 'ProjectStatisticsTimeConverted',
        'conversions': 'ProjectStatisticsConversions'
    }

    attribute_map = {
        'project_id': 'project_id',
        'time_converted': 'time_converted',
        'conversions': 'conversions'
    }

    def __init__(self, project_id=None, time_converted=None, conversions=None):  # noqa: E501
        """ProjectStatistics - a model defined in Swagger"""  # noqa: E501
        self._project_id = None
        self._time_converted = None
        self._conversions = None
        self.discriminator = None
        if project_id is not None:
            self.project_id = project_id
        if time_converted is not None:
            self.time_converted = time_converted
        if conversions is not None:
            self.conversions = conversions

    @property
    def project_id(self):
        """Gets the project_id of this ProjectStatistics.  # noqa: E501

        The unique identifier for the project.  # noqa: E501

        :return: The project_id of this ProjectStatistics.  # noqa: E501
        :rtype: str
        """
        return self._project_id

    @project_id.setter
    def project_id(self, project_id):
        """Sets the project_id of this ProjectStatistics.

        The unique identifier for the project.  # noqa: E501

        :param project_id: The project_id of this ProjectStatistics.  # noqa: E501
        :type: str
        """

        self._project_id = project_id

    @property
    def time_converted(self):
        """Gets the time_converted of this ProjectStatistics.  # noqa: E501


        :return: The time_converted of this ProjectStatistics.  # noqa: E501
        :rtype: ProjectStatisticsTimeConverted
        """
        return self._time_converted

    @time_converted.setter
    def time_converted(self, time_converted):
        """Sets the time_converted of this ProjectStatistics.


        :param time_converted: The time_converted of this ProjectStatistics.  # noqa: E501
        :type: ProjectStatisticsTimeConverted
        """

        self._time_converted = time_converted

    @property
    def conversions(self):
        """Gets the conversions of this ProjectStatistics.  # noqa: E501


        :return: The conversions of this ProjectStatistics.  # noqa: E501
        :rtype: ProjectStatisticsConversions
        """
        return self._conversions

    @conversions.setter
    def conversions(self, conversions):
        """Sets the conversions of this ProjectStatistics.


        :param conversions: The conversions of this ProjectStatistics.  # noqa: E501
        :type: ProjectStatisticsConversions
        """

        self._conversions = conversions

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value
        if issubclass(ProjectStatistics, dict):
            for key, value in self.items():
                result[key] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, ProjectStatistics):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        return not self == other
