# coding: utf-8

"""
    Respeecher API

    API for interacting with Respeecher services, including key and session management, and calibration functionalities.  # noqa: E501

    OpenAPI spec version: 1.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

import pprint
import re  # noqa: F401

import six

class VoiceSettingsRequest(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'voice_id': 'str',
        'narration_style_id': 'str',
        'accent_id': 'str',
        'semitones_correction': 'int'
    }

    attribute_map = {
        'voice_id': 'voice_id',
        'narration_style_id': 'narration_style_id',
        'accent_id': 'accent_id',
        'semitones_correction': 'semitones_correction'
    }

    def __init__(self, voice_id=None, narration_style_id=None, accent_id=None, semitones_correction=None):  # noqa: E501
        """VoiceSettingsRequest - a model defined in Swagger"""  # noqa: E501
        self._voice_id = None
        self._narration_style_id = None
        self._accent_id = None
        self._semitones_correction = None
        self.discriminator = None
        if voice_id is not None:
            self.voice_id = voice_id
        if narration_style_id is not None:
            self.narration_style_id = narration_style_id
        if accent_id is not None:
            self.accent_id = accent_id
        if semitones_correction is not None:
            self.semitones_correction = semitones_correction

    @property
    def voice_id(self):
        """Gets the voice_id of this VoiceSettingsRequest.  # noqa: E501


        :return: The voice_id of this VoiceSettingsRequest.  # noqa: E501
        :rtype: str
        """
        return self._voice_id

    @voice_id.setter
    def voice_id(self, voice_id):
        """Sets the voice_id of this VoiceSettingsRequest.


        :param voice_id: The voice_id of this VoiceSettingsRequest.  # noqa: E501
        :type: str
        """

        self._voice_id = voice_id

    @property
    def narration_style_id(self):
        """Gets the narration_style_id of this VoiceSettingsRequest.  # noqa: E501


        :return: The narration_style_id of this VoiceSettingsRequest.  # noqa: E501
        :rtype: str
        """
        return self._narration_style_id

    @narration_style_id.setter
    def narration_style_id(self, narration_style_id):
        """Sets the narration_style_id of this VoiceSettingsRequest.


        :param narration_style_id: The narration_style_id of this VoiceSettingsRequest.  # noqa: E501
        :type: str
        """

        self._narration_style_id = narration_style_id

    @property
    def accent_id(self):
        """Gets the accent_id of this VoiceSettingsRequest.  # noqa: E501


        :return: The accent_id of this VoiceSettingsRequest.  # noqa: E501
        :rtype: str
        """
        return self._accent_id

    @accent_id.setter
    def accent_id(self, accent_id):
        """Sets the accent_id of this VoiceSettingsRequest.


        :param accent_id: The accent_id of this VoiceSettingsRequest.  # noqa: E501
        :type: str
        """

        self._accent_id = accent_id

    @property
    def semitones_correction(self):
        """Gets the semitones_correction of this VoiceSettingsRequest.  # noqa: E501


        :return: The semitones_correction of this VoiceSettingsRequest.  # noqa: E501
        :rtype: int
        """
        return self._semitones_correction

    @semitones_correction.setter
    def semitones_correction(self, semitones_correction):
        """Sets the semitones_correction of this VoiceSettingsRequest.


        :param semitones_correction: The semitones_correction of this VoiceSettingsRequest.  # noqa: E501
        :type: int
        """

        self._semitones_correction = semitones_correction

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value
        if issubclass(VoiceSettingsRequest, dict):
            for key, value in self.items():
                result[key] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, VoiceSettingsRequest):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        return not self == other
